import { User } from "@/types";

export const usersDummy: User[] = [
  {
    id: 1,
    name: "Frieren",
    email: "frieren@example.com",
    is_active: true,
    image: "https://cdn.rafled.com/anime-icons/images/KplVpfqNuadpBc4uXjq8nrMZZPAXi4OK.jpg",
    role: "Frontend Developer",
    projectName: "Company Website",
    budget: "4.2K",
    status: "Active",
  },
  {
    id: 2,
    name: "Himmel Bin Abdul Rojak",
    email: "himmel@example.com",
    is_active: false,
    image: "https://i.pinimg.com/736x/f6/f5/d1/f6f5d1e5a548e8eeaf08cfeede6638e8.jpg",
    role: "UI/UX Designer",
    projectName: "Mobile App",
    budget: "999.9K",
    status: "Pending",
  },
  {
    id: 3,
    name: "Fern",
    email: "fern@example.com",
    is_active: true,
    image: "https://cdn.rafled.com/anime-icons/images/GzRsyqEdS1hzi6CvR809AnlTjejD8mDi.jpg",
    role: "Backend Developer",
    projectName: "API System",
    budget: "12.1K",
    status: "Active",
  },
  {
    id: 4,
    name: "stark",
    email: "stark@example.com",
    is_active: true,
    image: "https://i.pinimg.com/736x/b1/e4/e7/b1e4e7b71164e0b3e80e6b44958d3a98.jpg",
    role: "Project Manager",
    projectName: "Dashboard Admin",
    budget: "9.5K",
    status: "Cancel",
  },
  {
    id: 5,
    name: "Heiter",
    email: "heiter@example.com",
    is_active: false,
    image: "https://otakotaku.com/asset/img/character/2025/12/heiter-6938186abbb52p.jpg",
    role: "DevOps Engineer",
    projectName: "Cloud Migration",
    budget: "15.3K",
    status: "Pending",
  },
  {
    id: 6,
    name: "Eisen",
    email: "eisen@example.com",
    is_active: true,
    image: "https://i.pinimg.com/736x/6f/f1/6f/6ff16ff53e93c3dfcae7cc824a250f59.jpg",
    role: "QA Engineer",
    projectName: "Automation Testing",
    budget: "3.4K",
    status: "Active",
  },
  {
    id: 7,
    name: "Serie",
    email: "serie@example.com",
    is_active: true,
    image: "https://i.pinimg.com/1200x/8a/76/52/8a7652ef4d09d62f128a9511807efe7e.jpg",
    role: "Fullstack Developer",
    projectName: "E-Commerce",
    budget: "18.7K",
    status: "Active",
  },
  {
    id: 8,
    name: "Flamme",
    email: "flamme@example.com",
    is_active: false,
    image: "https://i.pinimg.com/originals/94/65/95/946595e61b9664ece5e23c3e9ef8baa6.jpg",
    role: "Marketing Specialist",
    projectName: "SEO Campaign",
    budget: "6.1K",
    status: "Cancel",
  },
  {
    id: 9,
    name: "Aura",
    email: "aura@example.com",
    is_active: true,
    image: "https://i.pinimg.com/736x/69/45/d8/6945d8aeddcb3bb32bcbab200916b762.jpg",
    role: "Data Analyst",
    projectName: "Data Warehouse",
    budget: "11.9K",
    status: "Pending",
  },
  {
    id: 10,
    name: "Ubel",
    email: "ubel@example.com",
    is_active: true,
    image: "https://i.pinimg.com/originals/c0/d3/d1/c0d3d1f0d1e1ef57b75c327df33311cb.jpg",
    role: "Scrum Master",
    projectName: "Agile Setup",
    budget: "5.6K",
    status: "Active",
  },
  {
    id: 11,
    name: "Denken",
    email: "denken@example.com",
    is_active: false,
    image: "https://i.pinimg.com/736x/12/6b/3a/126b3addb9cdefe45b9e587ac7d25c88.jpg",
    role: "Security Engineer",
    projectName: "Penetration Test",
    budget: "13.2K",
    status: "Cancel",
  },
  {
    id: 12,
    name: "Wirbel",
    email: "wirbel@example.com",
    is_active: true,
    image: "https://i.pinimg.com/736x/dc/0b/10/dc0b1063c14c659f50464e411f05857f.jpg",
    role: "Product Owner",
    projectName: "SaaS Platform",
    budget: "21.4K",
    status: "Active",
  },
];