export const RESOURCES = {
  ROLE: "role",
  DIVISION: "division",
  USER: "user",
  SETTING: "setting",
  POSITION: "position",
  ALLOWANCE: "allowance",
  ATTENDANCE: "attendance",
  ATTENDANCE_CORRECTION: "attendance-correction",
  HOLIDAY: "holiday",
  WORK_SCHEDULE: "work-schedule",
  EMPLOYEE_WORK_SCHEDULE: "employee-work-schedule",
  SHIFT_TEMPLATE: "shift-template",
  EMPLOYEE_SHIFT: "employee-shift",
  LEAVE_TYPES: "leave-type",
  LEAVE: "leave",
  EARLY_LEAVE: "early-leave",
  ATTENDANCE_REQUEST: "attendance-request",
  OVERTIME: "overtime",
  PAYROLL: "payroll",
  DASHBOARD: "dashboard",
  ASSESSMENT_CATEGORY: "assessment-category",
  ASSESSMENT: "assessment",
} as const;
